"""Execution coordinator for paper orders generated by the trading runtime."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from app.broker.base import BrokerInterface, OrderRequest, OrderResult
from app.paper.trade_logger import TradeLogger
from app.strategies.base import SignalType, StrategySignal


class ExecutionEngine:
    """Routes normalized strategy signals into a pending next-bar-open queue."""

    def __init__(
        self,
        broker: BrokerInterface,
        trade_logger: Optional[TradeLogger] = None,
        blocked_entry_hours: Optional[set[int]] = None,
    ) -> None:
        """Stores the broker dependency and queue state."""

        self._broker = broker
        self._trade_logger = trade_logger
        self._blocked_entry_hours = set(blocked_entry_hours or {15, 16, 17})
        self.pending_orders = []  # type: List[Dict[str, Any]]
        self._ignored_execution_count = 0

    def submit_entry(self, request: OrderRequest) -> OrderResult:
        """Submits an entry order using the correct broker side method."""

        if request.side.lower() == "buy":
            return self._broker.buy(request)
        return self._broker.sell(request)

    def submit_exit(self, symbol: str) -> Optional[OrderResult]:
        """Submits a close request for an existing position."""

        return self._broker.close_position(symbol)

    def execute_signal(self, signal: StrategySignal) -> Optional[OrderResult]:
        """Preserves the old interface by queueing the signal for next-bar processing."""

        self.queue_signal(signal)
        return None

    def queue_signal(self, signal: StrategySignal) -> Optional[Dict[str, Any]]:
        """Queues a non-NONE signal for execution at the next bar open."""

        if signal.signal_type == SignalType.NONE:
            return None

        order = {
            "signal_type": signal.signal_type.value,
            "symbol": signal.symbol,
            "signal_timestamp": signal.timestamp.isoformat(),
            "signal_price": signal.price,
            "reason": signal.reason,
            "metadata": dict(signal.metadata),
            "qty": 1,
        }
        self.pending_orders.append(order)
        if self._trade_logger is not None:
            self._trade_logger.log_pending_order(order)
        return order

    def process_pending_orders_at_bar_open(self, bar: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Processes all queued orders using the current bar open price."""

        if not self.pending_orders:
            return []

        execution_price = float(bar["open"])
        pending_orders = list(self.pending_orders)
        self.pending_orders = []
        executions = []

        for order in pending_orders:
            execution = self._process_single_pending_order(
                order,
                bar,
                execution_price,
            )
            if execution is not None:
                executions.append(execution)
        return executions

    def get_pending_order_count(self) -> int:
        """Returns the number of queued pending orders."""

        return len(self.pending_orders)

    def get_ignored_execution_count(self) -> int:
        """Returns how many executions were ignored this runtime."""

        return self._ignored_execution_count

    def update_open_position_from_bar(self, bar: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Updates open-position excursion data on each fully processed bar."""

        updater = getattr(self._broker, "update_open_position_from_bar", None)
        if updater is None or not callable(updater):
            return None
        position = updater(bar)
        if position is not None and self._trade_logger is not None:
            self._trade_logger.log_position_snapshot(position, bar)
        return position

    def get_open_position(self) -> Optional[Dict[str, Any]]:
        """Returns the broker's currently open position if one exists."""

        getter = getattr(self._broker, "get_open_position", None)
        if getter is None or not callable(getter):
            return None
        return getter()

    def get_closed_trades(self) -> List[Dict[str, Any]]:
        """Returns broker-tracked closed trades."""

        getter = getattr(self._broker, "get_closed_trades", None)
        if getter is None or not callable(getter):
            return []
        return getter()

    def get_realized_pnl(self) -> float:
        """Returns cumulative realized PnL from the broker."""

        getter = getattr(self._broker, "get_realized_pnl", None)
        if getter is None or not callable(getter):
            return 0.0
        return float(getter())

    def _process_single_pending_order(
        self,
        order: Dict[str, Any],
        bar: Dict[str, Any],
        execution_price: float,
    ) -> Optional[Dict[str, Any]]:
        """Processes a single queued order at the current bar open price."""

        signal_type = str(order.get("signal_type", ""))
        if self._should_cancel_entry_order(signal_type, bar):
            cancellation = self._build_cancelled_order(order, bar)
            self._log_execution(cancellation, bar)
            return cancellation

        execution = {
            "status": "executed",
            "signal_type": signal_type,
            "symbol": order.get("symbol", ""),
            "signal_timestamp": order.get("signal_timestamp", ""),
            "execution_timestamp": str(bar.get("timestamp", "")),
            "execution_price": execution_price,
            "reason": order.get("reason", ""),
            "metadata": dict(order.get("metadata", {})),
            "qty": int(order.get("qty", 1) or 1),
        }

        if signal_type == SignalType.LONG_ENTRY.value:
            self._handle_entry(execution, side="buy")
        elif signal_type == SignalType.SHORT_ENTRY.value:
            self._handle_entry(execution, side="sell")
        elif signal_type == SignalType.LONG_EXIT.value:
            self._handle_exit(execution, expected_signal_type=SignalType.LONG_EXIT.value)
        elif signal_type == SignalType.SHORT_EXIT.value:
            self._handle_exit(execution, expected_signal_type=SignalType.SHORT_EXIT.value)
        else:
            return None

        if execution["status"] == "ignored":
            self._ignored_execution_count += 1
        self._log_execution(execution, bar)
        return execution

    def _handle_entry(self, execution: Dict[str, Any], side: str) -> None:
        """Attempts to open a new position from an entry execution."""

        _ = OrderRequest(
            symbol=str(execution.get("symbol", "")),
            side=side,
            quantity=int(execution.get("qty", 1) or 1),
            price=float(execution.get("execution_price", 0.0)),
            strategy_tag=str(execution.get("reason", "")),
        )
        opener = getattr(self._broker, "open_position", None)
        if opener is None or not callable(opener):
            execution["status"] = "ignored"
            execution["metadata"]["ignore_reason"] = "broker_missing_open_position"
            return
        position = opener(execution)
        if position is None:
            execution["status"] = "ignored"
            execution["metadata"]["ignore_reason"] = "existing_position"
            return
        execution["position"] = position

    def _handle_exit(self, execution: Dict[str, Any], expected_signal_type: str) -> None:
        """Attempts to close the current position from an exit execution."""

        if str(execution.get("signal_type", "")) != expected_signal_type:
            execution["status"] = "ignored"
            execution["metadata"]["ignore_reason"] = "unexpected_exit_signal"
            return
        closer = getattr(self._broker, "close_position", None)
        if closer is None or not callable(closer):
            execution["status"] = "ignored"
            execution["metadata"]["ignore_reason"] = "broker_missing_close_position"
            return
        trade = closer(execution)
        if trade is None:
            execution["status"] = "ignored"
            execution["metadata"]["ignore_reason"] = "no_matching_position"
            return
        execution["trade"] = trade
        if self._trade_logger is not None:
            self._trade_logger.log_trade(trade)

    def _should_cancel_entry_order(
        self,
        signal_type: object,
        bar: Dict[str, Any],
    ) -> bool:
        """Returns whether a queued entry should be cancelled at this bar open."""

        return (
            str(signal_type) in {
                SignalType.LONG_ENTRY.value,
                SignalType.SHORT_ENTRY.value,
            }
            and self._get_bar_hour(bar) in self._blocked_entry_hours
        )

    def _build_cancelled_order(
        self,
        order: Dict[str, Any],
        bar: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Builds a cancellation event for a blocked next-bar-hour entry."""

        metadata = dict(order.get("metadata", {}))
        metadata["entry_blocked_next_bar_hour"] = self._get_bar_hour(bar)
        metadata["blocked_entry_hours"] = sorted(self._blocked_entry_hours)
        metadata["order_status"] = "cancelled"
        metadata["cancel_reason"] = "blocked_entry_hour"
        return {
            "status": "cancelled",
            "signal_type": str(order.get("signal_type", "")),
            "symbol": order.get("symbol", ""),
            "signal_timestamp": order.get("signal_timestamp", ""),
            "execution_timestamp": str(bar.get("timestamp", "")),
            "execution_price": "",
            "reason": "blocked_entry_hour",
            "metadata": metadata,
            "qty": int(order.get("qty", 1) or 1),
        }

    def _log_execution(self, execution: Dict[str, Any], bar: Dict[str, Any]) -> None:
        """Persists an order execution event when logging is enabled."""

        if self._trade_logger is not None:
            self._trade_logger.log_order_execution(execution, bar)

    def _get_bar_hour(self, bar: Dict[str, Any]) -> int:
        """Returns the hour of the pending execution bar timestamp."""

        return datetime.fromisoformat(str(bar.get("timestamp", ""))).hour
